#!/bin/bash
clear
 hour=14
 min=00
 sec=00
        while [ $hour -ge 0 ]; do
                 while [ $min -ge 0 ]; do
                         while [ $sec -ge 0 ]; do
                                 echo -ne "$hour:$min:$sec\033[0K\r"
				 echo ""
				 echo -ne "This is how long is left in your day.\nYou should sleep when this reaches 0, for your health.\n "
                                 let "sec=sec-1"
                                 sleep 1
				 clear
                         done
                         sec=59
                         let "min=min-1"
                 done
                 min=59
                 let "hour=hour-1"
         done