#!/bin/bash
# dishonored-too-dark-fix.sh

killall redshift-gtk
killall redshift
pkill redshift
pkill redshift-gtk
clear

# damn film grain

while true; do sleep 0.01s && xgamma -gamma 1.4 && echo "" && echo "damn film grain" && echo "" && echo "Ctrl+C to stop it, run this command once you're done to reset to default:" && echo "xgamma -gamma 1.0" && echo ""; done

# Ctrl+C to stop it, run this command once you're done to reset to default:
xgamma -gamma 1.0

