#!/bin/bash
# hl2-half-life-2-ravenholm-too-dark-fix.sh

killall redshift-gtk
killall redshift
pkill redshift
pkill redshift-gtk
clear

# damn film grain

while true; do sleep 0.01s && xgamma -gamma 1.5 && echo "" && echo "Remember: sv_infinite_aux_power 1 isn't actually flagged as a cheat, use it for forever flashlight!" && echo "and also snd_musicvolume 0 can help reduce spooky!" && echo "" && echo "Ctrl+C to stop it, run this command once you're done to reset to default:" && echo "xgamma -gamma 1.0" && echo ""; done

# Ctrl+C to stop it, run this command once you're done to reset to default:
xgamma -gamma 1.0

