#!/bin/bash
# Install IceWM (Fedora)
echo "Install IceWM (Fedora)"

set +x

cd "$(dirname "$0")"

sudo dnf install -y lzip
sudo dnf install -y g++

sudo dnf install -y icewm
sudo dnf install -y icewm-clearlooks
sudo dnf install -y icewm-data
sudo dnf install -y icewm-minimal-session
sudo dnf install -y icewm-themes

wget https://ice-wm.org/scripts/os-depends.sh
sudo bash -x ./os-depends.sh

set +x

echo "All done. Reboot please."
