#!/bin/bash
# make-sentence.sh

# thank you Mike Willis of Mike's blag for this code, I only
#  very sloppily made it loop, and made it append to a text file as a sentence.

# i only tested this on mac OS 10.6.8 on bash 5.1, so, ymmv.

clear
echo "[$(date)] Working..."
clear

function randword {
WORDFILE=/usr/share/dict/words
# seed random from pid
RANDOM=$$;
# using cat means wc outputs only a number, not number followed by filename
lines=$(cat $WORDFILE  | wc -l);
rnum=$((RANDOM*RANDOM%$lines+1));
sed -n "$rnum p" $WORDFILE;
}

printf %s "$(randword) " | tr [:upper:] [:lower:] | fold -w 80 >> sentence.txt
fold -w 80 -s sentence.txt
echo ""
echo ""
sleep 2s
echo "[$(date)] Working..."
sleep 1s
bash make-sentence.sh