#!/bin/bash

# steam-with-brain-fog.sh v10 final

# deps: xdotool, wmctrl


xdotool keyup Up
xdotool keyup Down




while true
do
  clear
  sleep 0.1s # REQUIRED SO STEAM CAN LOAD THE ITEM IN TIME
  sleep 0.1s # REQUIRED SO STEAM CAN LOAD THE ITEM IN TIME
  killall io.elementary.notifications
  clear
  /usr/bin/io.elementary.notifications &
  clear
  wmctrl -a "Steam"
  sleep 0.1s # REQUIRED SO STEAM CAN LOAD THE ITEM IN TIME
  xdotool keydown Down
  xdotool keyup Down
  sleep 0.25s # REQUIRED SO STEAM CAN LOAD THE ITEM IN TIME
  wmctrl -a "$(whoami)@$(whoami)-PC: ~"
  clear
  echo "WAIT"
  wmctrl -a "$(whoami)@$(whoami)-PC: ~"
  sleep 0s
  wmctrl -a "$(whoami)@$(whoami)-PC: ~"
  sleep 0s
  wmctrl -a "$(whoami)@$(whoami)-PC: ~"
  clear
  echo "WAIT"
  wmctrl -a "$(whoami)@$(whoami)-PC: ~"
  sleep 0.1s # REQUIRED SO STEAM CAN LOAD THE ITEM IN TIME
    sleep 0.1s # REQUIRED SO STEAM CAN LOAD THE ITEM IN TIME
        sleep 0.1s # REQUIRED SO STEAM CAN LOAD THE ITEM IN TIME
                sleep 0.1s # REQUIRED SO STEAM CAN LOAD THE ITEM IN TIME

sleep 1s # REQUIRED SO STEAM CAN LOAD THE ITEM IN TIME
  wmctrl -a "$(whoami)@$(whoami)-PC: ~"
  clear
  echo "WAIT"
  sleep 0.1s
  clear
  echo "WAIT"
  
  killall speaker-test
  clear
  sleep 0.1s
  sleep 0.1s # REQUIRED SO STEAM CAN LOAD THE ITEM IN TIME
  #notify-send --urgency "Critical" --app-name "How about this game?" --icon /usr/share/icons/Adwaita/256x256/legacy/dialog-warning.png --expire-time 429496729 "What do you think?"
wmctrl -Fa 'Terminal'
xdotool windowactivate `xdotool search --onlyvisible --class Terminal`
sleep 0.1s
wmctrl -Fa 'Terminal'
xdotool windowactivate `xdotool search --onlyvisible --class Terminal`
( speaker-test -t sine -f 880 &> /dev/null )& pid=$! ; sleep 0.3s ; kill -9 $pid
  wmctrl -Fa 'Terminal'
xdotool windowactivate `xdotool search --onlyvisible --class Terminal`
  clear
  echo "What do you think?"
  echo " [ENTER: next game]"
  read -p " [Mouse: install game]"
done
xdotool keyup Down




xdotool keyup Up
xdotool keyup Down
xdotool keyup Down
# eof
exit


